# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "rextract"
  s.version = "0.1.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["JT Zemp"]
  s.date = "2012-03-12"
  s.description = "A web scraping framework based on Mechanize using the Dirt pattern. See https://github.com/jtzemp/rextract for more details."
  s.email = "jtzemp@gmail.com"
  s.executables = ["rextract"]
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "bin/rextract",
    "lib/rextract.rb",
    "lib/rextract/browser.rb",
    "lib/rextract/parser.rb",
    "lib/rextract/spider.rb",
    "rextract.gemspec",
    "spec/rextract/browser_spec.rb",
    "spec/rextract/parser_spec.rb",
    "spec/rextract/spider_spec.rb",
    "spec/rextract_spec.rb",
    "spec/spec_helper.rb",
    "templates/app/run",
    "templates/job/%job_name%.rb.tt",
    "templates/job/parser.rb.tt",
    "templates/job/spider.rb.tt",
    "templates/test.thor"
  ]
  s.homepage = "http://github.com/jtzemp/rextract"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.11"
  s.summary = "A web scraping framework based on Mechanize using the Dirt pattern. See https://github.com/jtzemp/rextract for more details."
  s.test_files = [
    "spec/rextract/browser_spec.rb",
    "spec/rextract/parser_spec.rb",
    "spec/rextract/spider_spec.rb",
    "spec/rextract_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mechanize>, ["~> 2.3"])
      s.add_runtime_dependency(%q<nokogiri>, ["~> 1.4"])
      s.add_runtime_dependency(%q<thor>, ["~> 0.14"])
      s.add_runtime_dependency(%q<activesupport>, ["~> 3.2"])
      s.add_runtime_dependency(%q<i18n>, ["= 0.6.0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<fakeweb>, ["= 1.3.0"])
      s.add_development_dependency(%q<ruby-debug>, ["= 0.10.4"])
      s.add_development_dependency(%q<ruby-debug19>, ["= 0.11.6"])
    else
      s.add_dependency(%q<mechanize>, ["~> 2.3"])
      s.add_dependency(%q<nokogiri>, ["~> 1.4"])
      s.add_dependency(%q<thor>, ["~> 0.14"])
      s.add_dependency(%q<activesupport>, ["~> 3.2"])
      s.add_dependency(%q<i18n>, ["= 0.6.0"])
      s.add_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<fakeweb>, ["= 1.3.0"])
      s.add_dependency(%q<ruby-debug>, ["= 0.10.4"])
      s.add_dependency(%q<ruby-debug19>, ["= 0.11.6"])
    end
  else
    s.add_dependency(%q<mechanize>, ["~> 2.3"])
    s.add_dependency(%q<nokogiri>, ["~> 1.4"])
    s.add_dependency(%q<thor>, ["~> 0.14"])
    s.add_dependency(%q<activesupport>, ["~> 3.2"])
    s.add_dependency(%q<i18n>, ["= 0.6.0"])
    s.add_dependency(%q<rspec>, ["~> 2.8.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<fakeweb>, ["= 1.3.0"])
    s.add_dependency(%q<ruby-debug>, ["= 0.10.4"])
    s.add_dependency(%q<ruby-debug19>, ["= 0.11.6"])
  end
end

