# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rextract}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["JT Zemp"]
  s.date = %q{2011-01-20}
  s.default_executable = %q{rextract}
  summary = %q{A web scraping framework based on Mechanize using the Dirt (https://github.com/mthorley/dirt) pattern.}
  s.description = summary
  s.email = %q{jtzemp@gmail.com}
  s.executables = ["rextract"]
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "bin/rextract",
    "lib/rextract.rb",
    "lib/rextract/browser.rb",
    "lib/rextract/parser.rb",
    "lib/rextract/spider.rb",
    "spec/rextract/browser_spec.rb",
    "spec/rextract/parser_spec.rb",
    "spec/rextract/spider_spec.rb",
    "spec/rextract_spec.rb",
    "spec/spec_helper.rb",
    "templates/job/%name%/job.rb.tt",
    "templates/job/%name%/parser.rb.tt",
    "templates/job/%name%/spider.rb.tt",
    "templates/job/run"
  ]
  s.homepage = %q{http://github.com/jtzemp/rextract}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = summary
  s.test_files = [
    "spec/rextract/browser_spec.rb",
    "spec/rextract/parser_spec.rb",
    "spec/rextract/spider_spec.rb",
    "spec/rextract_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mechanize>, ["~> 1.0.0"])
      s.add_runtime_dependency(%q<nokogiri>, ["~> 1.4.4"])
      s.add_runtime_dependency(%q<thor>, ["= 0.14.4"])
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<fakeweb>, ["= 1.3.0"])
      s.add_development_dependency(%q<ruby-debug>, ["= 0.10.4"])
      s.add_development_dependency(%q<ruby-debug19>, ["= 0.11.6"])
    else
      s.add_dependency(%q<mechanize>, ["~> 1.0.0"])
      s.add_dependency(%q<nokogiri>, ["~> 1.4.4"])
      s.add_dependency(%q<thor>, ["= 0.14.4"])
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<fakeweb>, ["= 1.3.0"])
      s.add_dependency(%q<ruby-debug>, ["= 0.10.4"])
      s.add_dependency(%q<ruby-debug19>, ["= 0.11.6"])
    end
  else
    s.add_dependency(%q<mechanize>, ["~> 1.0.0"])
    s.add_dependency(%q<nokogiri>, ["~> 1.4.4"])
    s.add_dependency(%q<thor>, ["= 0.14.4"])
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<fakeweb>, ["= 1.3.0"])
    s.add_dependency(%q<ruby-debug>, ["= 0.10.4"])
    s.add_dependency(%q<ruby-debug19>, ["= 0.11.6"])
  end
end

